### ISSUE TITLE
Visible Icon appearing in full screen video mode

### ISSUE THREAD

**Issue by Avadaime** [DeveloperMDCM/Youtube-tools-extension#33]
At least make it possible to remove/disable it in the settings by default, it's kinda ruining clean view when watching videos.
Script version - 2.2.80
Settings bar version of YouTube Tools - v1.0 

![image](https://github.com/user-attachments/assets/d77c6010-4339-4609-addd-895ae2b2e72c)

**Comment by DeveloperMDCM** [comment]
new update fixed
