### ISSUE TITLE
something wrong with the download

### ISSUE THREAD

**Issue by 73Emilie** [DeveloperMDCM/Youtube-tools-extension#6]
<img width="912" alt="截屏2023-06-01 17 19 08" src="https://github.com/DeveloperMDCM/Youtube-tools-extension/assets/115063328/ff357b20-e33d-4a5a-ab16-5850f26edd72">

When the download is complete, how do I open the downloaded video? Every time I click "100% done," it redirects to a strange page.

**Comment by DeveloperMDCM** [comment]
Install ADGUARD  
https://adguard.com/es/adguard-browser-extension/overview.html
