### ISSUE TITLE
Need some improvement

### ISSUE THREAD

**Issue by martjay** [DeveloperMDCM/Youtube-tools-extension#7]
Many icons have damaged the original layout of YouTube. I don't think it would be better to change the title layout and display a hidden icon button below the introduction. Moving the mouse over this button will automatically expand all the icons. Would this be better?

![Snipaste_2023-06-22_09-10-59](https://github.com/DeveloperMDCM/Youtube-tools-extension/assets/44982189/c55dcb69-ea16-4d63-87bf-86e4bfd415ee)

**Comment by TbangIT** [comment]
In my repository I made some aesthetic/functional changes to the original script to use it personally, if you need it you can find it here: https://github.com/TbangIT/YTE-clear . The repository is in Italian, but i hope it can be used to modify the original layout and that it can be useful to the original developer

**Comment by martjay** [comment]
> In my repository I made some aesthetic/functional changes to the original script to use it personally, if you need it you can find it here: https://github.com/TbangIT/YTE-clear . The repository is in Italian, but i hope it can be used to modify the original layout and that it can be useful to the original developer

NOW, it's perfect. You are amazing. Thank you!

**Comment by DeveloperMDCM** [comment]
Of course I will take it into account in a future update. If you have new ideas please comment
